name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide details below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: "I would like folder-profiler to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how this feature would be used
      placeholder: "As a developer, I would use this to..."
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: If applicable, show how you would use this feature
      render: bash
      placeholder: |
        folder-profiler analyze /path --new-feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information or screenshots
